- name: Add Kubernetes apt key
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version_short }}/deb/Release.key | \
    gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes repo
  copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: |
      deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version_short }}/deb/ /

- name: Install kubelet, kubeadm, kubectl
  apt:
    name:
      - "kubelet={{ kubernetes_version }}"
      - "kubeadm={{ kubernetes_version }}"
      - "kubectl={{ kubernetes_version }}"
    state: present
    update_cache: yes

- name: Install jq (optional but used in scripts)
  apt:
    name: jq
    state: present

- name: Hold kube packages
  command: apt-mark hold {{ item }}
  loop:
    - kubelet
    - kubeadm
    - kubectl
    - cri-o

