---
- name: Fetch join command from master
  slurp:
    src: /tmp/kubeadm_join_cmd.sh
  delegate_to: k8s-master-1
  register: join_cmd_encoded

- name: Decode and save join command
  copy:
    content: "{{ join_cmd_encoded.content | b64decode }}"
    dest: /tmp/kubeadm_join_cmd.sh
    mode: '0755'

- name: Join Kubernetes cluster
  shell: bash /tmp/kubeadm_join_cmd.sh
  
