- name: Add Helm repo for JupyterHub
  command: helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/

- name: Update Helm repos
  command: helm repo update

- name: Create namespace for JupyterHub
  command: kubectl create namespace jhub --dry-run=client -o yaml | kubectl apply -f -

- name: Install JupyterHub with Helm
  command: >
    helm upgrade --install jhub jupyterhub/jupyterhub
    --namespace jhub
    --version=3.3.7
    -f {{ role_path }}/templates/values.yml
